name: Auto Setup Realtime Analytics Project

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate Project Structure
        run: |
          python << 'EOF'
          import os

          PROJECT = "realtime-analytics-app"

          FILES = {
            "apps/dashboard/pages/index.tsx": "export default function Dashboard(){return(<h1>Realtime Analytics</h1>)}",
            "apps/dashboard/lib/supabase.ts": "export const supabase = {}",
            "apps/tracking-api/pages/api/track.ts": "export default function handler(req,res){res.json({ok:true})}",
            "packages/tracking-script/tracking.js": "console.log('tracking active')",
            "database/schema.sql": "create table page_views(id uuid);",
            ".env.example": "",
            "README.md": "# Realtime Analytics App"
          }

          for path, content in FILES.items():
              full = os.path.join(PROJECT, path)
              os.makedirs(os.path.dirname(full), exist_ok=True)
              with open(full, "w") as f:
                  f.write(content)

          print("Project generated")
          EOF

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto generate realtime analytics project"
          git push
